---
driver:
  name: ec2
  publish:
    - 8100:80

provisioner:
  name: chef_solo

platforms:
  - name: AmazonLinux-201509
    driver:
      image_id: ami-383c1956
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[chef-for-rails::default]
    attributes:
