name 'chef-for-rails'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-for-rails'
long_description 'Installs/Configures chef-for-rails'
version '0.1.0'
